### ISSUE TITLE
react-native-svg（6.3.0） creash on Android when drag

### ISSUE THREAD

**Issue by zgatrying** [zgatrying/react-native-practices#26]
应用场景：利用react-native-svg实现了一个自定义组件ArcSlider（圆弧滑动条）。

问题描述：拖拽滚动条的滑块时偶尔会出现app闪退的情况，Chrome控制台也没有弹出报错信息。通过Android Studio  debugger模式，发现闪退时控制台打印了以下报错信息：
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.easemore.panel, PID: 5149
                  java.lang.NullPointerException
                      at com.horcrux.svg.RenderableShadowNode.getRegion(RenderableShadowNode.java:322)
                      at com.horcrux.svg.RenderableShadowNode.hitTest(RenderableShadowNode.java:300)
                      at com.horcrux.svg.SvgViewShadowNode.hitTest(SvgViewShadowNode.java:236)
                      at com.horcrux.svg.SvgView.dispatchTouchEvent(SvgView.java:97)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
                      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
                      at android.view.View.dispatchPointerEvent(View.java:7886)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                      at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                      at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                  	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:56
```

**Comment by zgatrying** [comment]
相关issue：

1.  [Crash on Android](https://github.com/react-native-community/react-native-svg/issues/784)

**Comment by zgatrying** [comment]
更新到6.5.3版本的react-native-svg，目前没有闪退现象。

**Comment by zgatrying** [comment]
`v6.3.0`版本与`v6.5.3`版本对比

SvgView.java有以下的不同
```java
//v6.3.0
    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        mTargetTag = getShadowNode().hitTest(new Point((int) ev.getX(), (int) ev.getY()));

        if (mTargetTag != -1) {
            handleTouchEvent(ev);
            return true;
        }

        return super.dispatchTouchEvent(ev);
    }

//6.5.3
    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        SvgViewShadowNode node = getShadowNode();
        if (node != null) {
            mTargetTag = node.hitTest(new Point((int) ev.getX(), (int) ev.getY()));
            if (mTargetTag != -1) {
                handleTouchEvent(ev);
                return true;
            }
        }

        return super.dispatchTouchEvent(ev);
    }
```

看上面的代码可以知道，6.5.3版本添加了对getShadowNode方法返回值是否为null的判断，从而避免了应用闪退的问题。

ps：6.5.3版本其他部分的更新请自行查看。[react-native-svg 6.5.3](https://github.com/react-native-community/react-native-svg/tree/v6.5.3)
